#!import "./module.yaml"

__mode : "dev"

__env :
    - "dev"
    - "demo"
    - "online"

__resuable :
    USER : "neoduan"
    PRJ_NAME : "date_fitness"
    LIST :
        - "devp1" : "sgp"
        - "devp2" : "zy"
        - "devp3" : "sxj"
        - "devp4" : "byd"

dev :
    #log 目前支持 file，syslog
    LOGKIT:
        - "LOG_MODE" : "file"
        - "LOG_PATH" : "/tmp/date_fitness.log"
    SVC_PORT : ":8384"
    DB_NAME : "127.0.0.1"
    DB_PORT : "6379"
    DB_NO   : "1"
    DB_USER : "dev"

demo :
    SVC_PORT : ":8083"
    DB_NAME : "127.0.0.1"
    DB_PORT : "6379"
    DB_NO   : "1"
    DB_USER : "demo"

online :
    SVC_PORT : ":80"
    DB_NAME : "10.10.71.37"
    DB_PORT : "49498"
    DB_NO   : "1"
    DB_USER : "online"
    DB_PWD  : "4iOKWsdJop5GOQ"
